### ISSUE TITLE
Changes to env vars are not triggering re-execution of buildpack

### ISSUE THREAD

**Issue by ciberkleid** [paketo-buildpacks/maven#1]
Example:

SETUP: Add to pom.xml:
```
    <profiles>
        <profile>
            <id>test</id>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <excludes>
                            <exclude>application.yml</exclude>
                        </excludes>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>
```

FIRST BUILD:
`pack build my-app --clear-cache`
TEST:
`docker run -it --entrypoint find my-app workspace -name application.yml`
workspace/BOOT-INF/classes/application.yml

SECOND BUILD:
`pack build my-app --env BP_MAVEN_BUILD_ARGUMENTS="-Dmaven.test.skip=true clean package -P test"`
TEST AGAIN:
`docker run -it --entrypoint find my-app workspace -name application.yml`
workspace/BOOT-INF/classes/application.yml

In contrast, on my local machine, a `./mvnw clean package -P test` results in a new jar without the excluded file.

Can also see the buildpack uses cache the second time:
```
[builder] Paketo Maven Buildpack 1.2.1
[builder]     Set $BP_MAVEN_SETTINGS to configure the contents of a settings.xml file. Default <none>.
[builder]     Set $BP_MAVEN_BUILD_ARGUMENTS to configure the arguments passed to the build system. Default -Dmaven.test.skip=true package.
[builder]     Set $BP_MAVEN_BUILT_MODULE to configure the module to find application artifact in. Default <ROOT>.
[builder]     Set $BP_MAVEN_BUILT_ARTIFACT to configure the built application artifact. Default target/*.[jw]ar.
[builder]     Creating cache directory /home/cnb/.m2
[builder]   Compiled Application: Reusing cached layer
[builder]   Removing source code
```

**Comment by nebhale** [comment]
Yep.  I'll incorporate these.  In the meantime `pack build ... --clear-cache` will work for you.

**Comment by nebhale** [comment]
Implementation to be completed as part of paketo-buildpacks/libbs#1

**Comment by ekcasey** [comment]
Resolved by the `libbs` upgrade included in https://github.com/paketo-buildpacks/maven/commit/a8bce8719478345bf5ca95f3da34a532a5230d4a

https://github.com/paketo-buildpacks/libbs/pull/3
