### ISSUE TITLE
how to add local dependecy

### ISSUE THREAD

**Issue by jeusdi** [paketo-buildpacks/maven#119]
Currently, this is my project structure:

```
.
├── hes-mpi-fhir-mongodb
│  ├── deployment.yaml
│  ├── pom.xml
│  ├── skaffold.yaml
│  └──  src
└── hes-spring-boot-core     <<< dependency requiered by hes-mpi-fhir-mongodb
   ├── pom.xml
   └── src

```

As you can see, I managing two maven projects.

My host building steps are:

```
$ hes-spring-boot-core > mvn clean install
$ hes-mpi-fhir-mongodb > mvn clean package
```

I mean, I first install `hes-spring-boot-core` into local repository and then I build `hes-mpi-fhir-mongodb`:

My `skaffold.yml` file is:

```lang-yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hes-mpi-fhir-mongodb
build:
  artifacts:
  - image: pom-xml-image
    buildpacks:
      builder: paketobuildpacks/builder:tiny 
deploy:
  kubectl:
    manifests:
    - deployment.yaml
```

I've also tried to perform:

    $ pack build fhir-mongo --builder paketobuildpacks/builder:tiny 

I'm getting this message, when I'm trying to build image:

```
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.841 s
[INFO] Finished at: 2022-01-03T22:43:22Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hes-mpi-fhir-mongodb-service: Could not resolve dependencies for project cat.gencat.catsalut.hes.mpi.fhir:hes-mpi-fhir-mongodb-service:jar:0.0.1-SNAPSHOT: Could not find artifact cat.gencat.catsalut.hes:hes-spring-boot-core:jar:1.0.6 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

It's getting me that maven builder is not able to find artifact `cat.gencat.catsalut.hes:hes-spring-boot-core:jar:1.0.6`.

How can I add this project a dependency?

I'm using skaffold `v1.35.1` and pack `0.23.0+git-0db2c77.build-3056`.

**Comment by dmikusa-pivotal** [comment]
Have you looked at turning your project into a multi-module project? That would let you build everything at once.

https://www.baeldung.com/maven-multi-module

**Comment by jeusdi** [comment]
I've recorded an [asciinema here](https://asciinema.org/connect/c807d03a-cd20-4fd5-9048-af06a5e87efd).

I'm performing 2 commands:

  1. `mvn clean package spring-boot:build-image -DskipTests`.
  2.  `pack build fhir-mongo --builder paketobuildpacks/builder:base`.

As you can see, `spring-boot:build-image` is using `paketobuildpacks/builder:base` underneath, and it's able to resolve dependency and create OCI image.

However, when I perform directly the `pack` comand using `--builder paketobuildpacks/builder:base` it's not able to resolve my local dependency.

Thanks for your comment.
Any ideas?

**Comment by dmikusa-pivotal** [comment]
Yes, there's a slight difference there.

>mvn clean package spring-boot:build-image -DskipTests

This builds the JAR file on your local machine, then builds the image from the JAR file.

>pack build fhir-mongo --builder paketobuildpacks/builder:base

This builds from source, so Maven runs in the container. 

If you want to build in the same manner as Spring Boot's Maven plugin, you'd need to add the `-p` argument to `pack build` and point to your JAR file.

Ex: `pack build fhir-mongo --builder paketobuildpacks/builder:base -p target/my-app-0.0.1.jar`

**Comment by jeusdi** [comment]
Thanks for your comment.

I've tried to look for a related documentation on [official buildpacks](https://buildpacks.io/docs/), but I'm not been able to look at any related information about `-p` or `--path` flag.

I've took a look on `pack build --help` and it's getting that:

```
-p, --path string                 Path to app dir or zip-formatted file (defaults to current working directory)
```

Where could I find any documentation/helping code/examples about this parameter?

**Comment by jeusdi** [comment]
I don't know if you could give your approach about how to use `buildpacks` with skkafold.

I mean, I don't quite figure out how to set `--path` into my buildpacks configuration.

Official skaffold documentation is telling me something about [artifact dependency](https://skaffold.dev/docs/pipeline-stages/builders/buildpacks/#configuration) and [dependences](https://skaffold.dev/docs/pipeline-stages/builders/buildpacks/#dependencies).

It's a bit messy for me.

Could you provide me some lights about it?

**Comment by dmikusa-pivotal** [comment]
>Where could I find any documentation/helping code/examples about this parameter?

I'm not sure there's any other docs. Path is just the path to what you want to build. If it's a directory, `pack` will provide all of those files to the buildpacks. If path points to a JAR/ZIP, `pack` will extract everything from that archive and provide it to the buildpacks.

>How have you detect the difference between spring-boot maven plugin and my previous pack build command?

That is something I've encountered before, but you can see the difference in the build output. When you run the build through Spring Boot, you'll see a different list of detected buildpacks (Maven CNB is not present because we're creating the image from compiled files) than what you see through `pack build` (Maven CNB is present because we got source code and need to build that). This is because of the difference in the input files.

**Comment by dmikusa-pivotal** [comment]
I haven't used Skaffold, but I can take a look at it and let you know. 

If it's helpful, we have docs for using Tilt, which I believe is a similar tool. See https://paketo.io/docs/howto/java/#using-tilt-with-paketo-buildpacks.

**Comment by dmikusa-pivotal** [comment]
>I mean, I don't quite figure out how to set --path into my buildpacks configuration.

I don't see a specific property for the path, but it seems to be exposed through the `context`.

>>To use Buildpacks, add a buildpack field to each artifact you specify in the artifacts part of the build section. context should be a path to your source.

This is quoted from [here](https://skaffold.dev/docs/pipeline-stages/builders/buildpacks/#configuration).

The `context` property seems to be off of the artifacts you configure. I couldn't find it referenced in the examples for buildpacks, but based on other examples that use context, it seems like you'd set it this way. I didn't have a chance to try, but you might give it a shot.

```
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    context: same/as/path/argument/for/pack/build
    buildpacks:
      builder: "paketobuildpacks/builder:base"
```

If that doesn't work, you would probably want to reach out for help with Skaffold. The tool is responsible for collecting that information and passing it through to the build, so the Skaffold team would have the most context on how you could do that.

Hope that helps!

**Comment by dmikusa-pivotal** [comment]
I believe all the questions here have been answered, so I'm going to close this. Feel free to open a new issue if you have more questions.
