### ISSUE TITLE
Document Include/Exclude files

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/maven#184]
With libbs 1.16.0, there is now support for including and excluding files. This needs to be documented in the Readme and also Paketo docs.

It needs to be documented for the other four libbs based Buildpacks as well.

**Comment by Carbonique** [comment]
Hi there, I'm having trouble getting my buildpacks working with BP_INCLUDE_FILES. It's not including the paths I want included.

In the readme I see that there's a default glob pattern. Can you point me to where this default is declared? I could not find it in this repository, nor could I find it in libbs.

**Comment by dmikusa** [comment]
@Carbonique can you open a new issue? I took a quick look and the README doc isn't 100% correct, there is actually no default at the moment. There may also be an issue because the default entry is not in buildpack.toml. Thanks

**Comment by Carbonique** [comment]
@dmikusa Will do! Might take a couple of days though.

**Comment by Carbonique** [comment]
@dmikusa sorry, I never opened an issue... Anyway, thanks for fixing the problem!
