### ISSUE TITLE
Look for settings.xml in <platform>/maven/settings.xml

### ISSUE THREAD

**Issue by nebhale** [paketo-buildpacks/maven#2]
Currently, in order to contribute a `settings.xml` file to the build, you set `$BP_MAVEN_SETTINGS` with the content of the file you’d like.  This content is then written to a temporary file and used during the build.  A better solution to this would be to expose it via a binding:
```plain
<platform>
└── bindings
    └── <name>
        └── metadata
            └── kind -> "maven"
        └── secret
            └── settings.xml
```

To make this change, the following steps (and possibly more) are required:

* [x] Remove configuration documentation
* [x] Update behavior documentation
* [x] Remove the configuration logging
* [x] Remove `settings` layer
* [x] Prepend location to arguments if it exists
* ~Include a hash of the contents of the file in the application’s expected metadata so that the compiled application will be invalidated if the contents of the file changes~ (moved to #3)

**Comment by ekcasey** [comment]
Resolved by https://github.com/paketo-buildpacks/maven/commit/8f987225f92f8b726090e69f8c1f44b5e8ecfb98
