### ISSUE TITLE
Make it easier to add to the default Maven arguments 

### ISSUE THREAD

**Issue by scottfrederick** [paketo-buildpacks/maven#226]
## Describe the Enhancement
It is currently possible to set the arguments that will be passed to Maven using the  `BP_MAVEN_BUILD_ARGUMENTS` environment variable. It is often desirable to add arguments to the Maven command without changing the default arguments. Activating [Maven build profiles](https://maven.apache.org/guides/introduction/introduction-to-profiles.html) is a common use case for this.

## Possible Solution
If Maven build profiles is considered the most common use case for adding arguments, then support for a new environment variable like `BP_MAVEN_ACTIVE_PROFILES`  could be added to the buildpack. The value of the environment variable would be a comma-separated list of profiles, and the buildpack would append `-P <value>` to the arguments list. 

A more general solution would be to add support for an environment variable like `BP_MAVEN_ADDITIONAL_BUILD_ARGUMENTS`. The value of this environment variable would be appended to the value of  `BP_MAVEN_BUILD_ARGUMENTS` to get the full list of arguments. 

## Motivation
Overriding the entire maven command line makes it difficult to keep the build argument in sync with the Paketo buildpack defaults. Being able to more simply add arguments would ensure that default are retained. 

Maven build profiles [can be activated in a Maven `settings.xml` file](https://maven.apache.org/settings.html#profiles) that can be provided to the buildpack as a binding or with `BP_MAVEN_SETTINGS_PATH`. This is a useful feature, but is a bit heavy-weight if the user only wants to activate build profiles.

**Comment by trisberg** [comment]
I would like to see a `BP_MAVEN_ACTIVE_PROFILES` option added.

**Comment by anthonydahanne** [comment]
hello @trisberg @scottfrederick 
Let me know if https://github.com/paketo-buildpacks/maven/pull/265 would work for both of you.
Thank you!
