### ISSUE TITLE
[builder] Error: Processing ... This may be the result of using an untrusted builder: failed with status code: 51

### ISSUE THREAD

**Issue by arthures11** [paketo-buildpacks/maven#229]
After downloads the errors:
`[builder] Error: Processing jar:file:///workspace/BOOT-INF/lib/gax-2.19.4.jar!/META-INF/native-image/com.google.api/gax/native-image.properties failed
[builder] Caused by: com.oracle.svm.driver.NativeImage$NativeImageError: Property 'Args' contains invalid entry '--add-modules=jdk.httpserver'
[builder] unable to invoke layer creator
[builder] unable to contribute native-image layer
[builder] error running build
[builder] exit status 1
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51`

appear and the builder stops
basically everything fails after long string of `[builder]   Executing native-image -H:+StaticExecutableWithDynamicLibC -H:Name=/layers/paketo-buildpacks_native-image/native-image`

## Motivations

i've been trying to make the native image(to reduce my image RAM usage) jar using:

`pack build sample_app --env BP_NATIVE_IMAGE=true --env BP_JVM_VERSION=17 --builder paketobuildpacks/builder:0.1.136-tiny`

while using  ` --builder paketobuildpacks/builder:base` instead of `tiny` one the errors are different such as:
`Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of ch.qos.logback.classic.Logger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=ch.qos.logback.classic.Logger.`

`paketobuildpacks/builder:full` on the other hand also granted those kind of errors:
`Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of ch.qos.logback.classic.Logger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=ch.qos.logback.classic.Logger.`

**Comment by pivotal-david-osullivan** [comment]
Can you please share the full output from the `pack build` command as well as your `pom.xml`?

The errors from the base & full builders seem to indicate that you are not using Spring Boot 3 with the Native Maven plugin.

**Comment by arthures11** [comment]
> Can you please share the full output from the `pack build` command as well as your `pom.xml`?
> 
> The errors from the base & full builders seem to indicate that you are not using Spring Boot 3 with the Native Maven plugin.

my pom: https://pastebin.com/G9bgexY4
so basically, nothing has worked for me. Packeto causes the errors ive just showed you, inbuilt spring boot 3+ native also had the same errors

BUT

i managed to make it work by making my own profile `nativeS` (spring 3+profile is called `native` with vustom BuildArgs like this:

![3d0a56b615b30d5e2f1f89eaa9ccdf7b](https://user-images.githubusercontent.com/58474213/214195519-1f120c97-6eb8-4815-b6ed-1a7d45a04983.png)



i am successfully creating an executable of my app this way
i am although getting other problems now like hibernate (fetch LAZY type) not working on native image or webjars bugging out(had to completely remove webjars from pom) but yeah it's for another topic and it's a hibernate - nativeimage so i shouldn't be talking about it in here

**Comment by pivotal-david-osullivan** [comment]
When building a native-image with Maven at the moment, you need to pass an additional argument to Maven to enable the `native` profile.

Can you try your original pom and add this to your pack build command?

`--env BP_MAVEN_BUILD_ARGUMENTS="-batch-mode -Dmaven.test.skip=true -Pnative --no-transfer-progress package"

**Comment by arthures11** [comment]
> When building a native-image with Maven at the moment, you need to pass an additional argument to Maven to enable the `native` profile.
> 
> Can you try your original pom and add this to your pack build command?
> 
> `--env BP_MAVEN_BUILD_ARGUMENTS="-batch-mode -Dmaven.test.skip=true -Pnative --no-transfer-progress package"`

wow!
`pack build sample_app --env BP_NATIVE_IMAGE=true --env BP_JVM_VERSION=17 --builder paketobuildpacks/builder:tiny--env BP_MAVEN_BUILD_ARGUMENTS="-batch-mode -Dmaven.test.skip=true -Pnative --no-transfer-progress package"`
worked for me, paketo now works like a charm, thank you!

**Comment by arthures11** [comment]
> When building a native-image with Maven at the moment, you need to pass an additional argument to Maven to enable the `native` profile.
> 
> Can you try your original pom and add this to your pack build command?
> 
> `--env BP_MAVEN_BUILD_ARGUMENTS="-batch-mode -Dmaven.test.skip=true -Pnative --no-transfer-progress package"`

observation:
paketo image seem to eat bit more RAM than manually created native image.
paketo takes around 100MB, while the manually created image just 60-80MB. Is there a way to make it even more optimal?
(for reference normal jar image needs around 500MB of ram)
