### ISSUE TITLE
Add support to specify the profile to use

### ISSUE THREAD

**Issue by jorgemoralespou** [paketo-buildpacks/maven#5]
My pom.xml has multiple profiles defined and I want a way to specify which one to use for my buildpack execution (and lifecycle).

**Comment by nebhale** [comment]
Do you have reason to believe that  [`BP_MAVEN_BUILD_ARGUMENTS=-Pnative-image -Dmaven.test.skip=true package`](https://github.com/paketo-buildpacks/maven#configuration) does not work?

**Comment by jorgemoralespou** [comment]
No. Just lack of documentation/examples :-(
Testing to see if this works.
