### ISSUE TITLE
How can we debug using IntelliJ the go binary detect or build ?

### ISSUE THREAD

**Issue by cmoulliard** [paketo-buildpacks/maven#68]
## Problem

How can we debug using IntelliJ the buildpack `detect` or `build` executable  ?

When the project is compiled and next dlv debugger launched by intellij, then we got this error `unsupported command ___detect` as the first argument passed is not `detect` but a temp file generated `/private/var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/___detect`

### Main code of libcnf

 `libcnf/main.go` is doing the following check

```
	switch c := filepath.Base(config.arguments[0]); c {
	case "build":
		Build(builder, options...)
	case "detect":
		Detect(detector, options...)
	default:
		config.exitHandler.Error(fmt.Errorf("unsupported command %s", c))
		return
	}
```

### Error generated by IntelliJ
```
GOROOT=/usr/local/Cellar/go/1.16.4/libexec #gosetup
GOPATH=/Users/cmoullia/code/golang #gosetup
/usr/local/Cellar/go/1.16.4/libexec/bin/go build -o /private/var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/___detect -gcflags all=-N -l /Users/cmoullia/code/cncf/paketo-debug/cmd/main/main.go #gosetup
"/Users/cmoullia/Library/Application Support/JetBrains/IntelliJIdea2021.1/plugins/go/lib/dlv/mac/dlv" --listen=0.0.0.0:59477 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /private/var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/___detect --
API server listening at: [::]:59477
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
Got a connection, launched process /private/var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/___detect (pid = 34778).
unsupported command ___detect
Exiting.
```

## Workaround

A possible workaround is to first build the go project

```
$home/code/cncf/paketo-maven
go build -o detect -gcflags all='-N -l' ./cmd/main/main.go
```

and next set 2 ENV VAR and use a remote debugger where we pass the location of `platform_dir` and `build.toml` used to export the plan

```
export CNB_BUILDPACK_DIR=/Users/cmoullia/code/cncf/paketo-maven
export CNB_STACK_ID=1
dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./detect ./tmp/platform ./tmp/build.toml
```

There is nevertheless an issue as the path of the application to be build is not customisable as during the execution of the `detect.go` fil, then the `ctx.Application.path` is set using `os.Getwd()`.

See: https://github.com/buildpacks/libcnb/blob/main/detect.go#L93

**Comment by dmikusa-pivotal** [comment]
I don't see how this is related to the Paketo Maven buildpack. I see what you're saying but it seems related to how `libcnb` is structured. I would suggest opening this under `libcnb`.

For what it's worth, it is usually easier to debug unit tests in Goland. That works very nicely & if you're having an issue then it inspires you to ensure that there is proper test coverage for the issue :) For the few cases where that has failed me, adding in some `fmt.Println`'s seems to get the job done.
