### ISSUE TITLE
[feature request] support multiple artifacts of different types.

### ISSUE THREAD

**Issue by vchrisb** [paketo-buildpacks/maven#76]
## What happened?
The maven buildpack is expecting a single build artifact of type either jar or war, which can be explicitly configured using `BP_MAVEN_BUILT_ARTIFACT`.
This artifact will be extracted and passed on to downstream buildpacks, like the native image buildpack.

The argument `BP_MAVEN_BUILD_ARGUMENTS="-Dmaven.test.skip=true -Dquarkus.package.type=native-sources package"`, to create Quarkus native image sources for a separate native image build, will generate multiple artifacts that are required to build a native image eventually with the native image buildpack:
```
target/native-sources/native-image.args
target/native-sources/lib/
target/native-sources/getting-started-1.0.0-SNAPSHOT-runner.jar
```
A potential solution for this usecase, and maybe others, is to allow passing a list of artifacts to `BP_MAVEN_BUILT_ARTIFACT`, which items are either extracted (jar or war) or copied (e.g. lib folder)

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.
TBS

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by jjbustamante** [comment]
I've been thinking about a possible solution to this issue, here is one idea. Based on my previous comment `BP_MAVEN_BUILT_ARTIFACT` is implemented right now as a regular expression also after evaluating this regular expression the current code is expecting just 1 artifact as result to be sent to the next phase (native-image for example). 

What about adding a new environment variable `BP_MAVEN_BUILT_ARTIFACT_FORMAT`, initially the values of this variable could be `reg` (Default, which means **regular expression**) or `folder`. When this value is set to folder it expects the other environment value. `BP_MAVEN_BUILT_ARTIFACT` to be set and also to point to some folder, for example `BP_MAVEN_BUILT_ARTIFACT="target/native-sources"`. In this case, the Buildpack will do the following actions: 

- It would compressed the whole folder and create 1 artifact
- It would send that artifact to the next Buildpack

With this solution we can:
-  Keep the current behavior as it is without changing the rule of expecting just 1 artifact
-  In the future extend the behavior enabling more formats to deal with

**Comment by jjbustamante** [comment]
Hi guys,

I would like to share some news about this issue.  I tried to take advantage of the [maven assembly plugin](http://maven.apache.org/plugins/maven-assembly-plugin/single-mojo.html) the idea is to have distribution xml in the maven paketo buildpack and inject that one during building time (not sure how to inject it yet). The distribution xml is going to create a .zip from the output folder defined by the user. 

This is an example.

```
pack build quarkus-getting-started-native \
          -e BP_NATIVE_IMAGE=true \
          -e BP_MAVEN_BUILD_ARGUMENTS="-Dquarkus.package.type=native-sources package" \ 
          -e BP_MAVEN_BUILT_ARTIFACT_FORMAT=zip \ 
          -e BP_MAVEN_BUILT_ARTIFACT="target/getting-started-1.0.0-SNAPSHOT-bin.zip" \ 
          -e BP_NATIVE_IMAGE_BUILD_ARGUMENTS="$(cat target/native-sources/native-image.args)" 
     -p .  (more buildpacks...)
```
Important to notice
- I am adding a new environment variable **BP_MAVEN_BUILT_ARTIFACT_FORMAT** which I think can be use in the future to add more format based on the maven assembly plugin
- I am using the native-image.args created by Quarkus to help on the native image creation

The  output is actually the file **getting-started-1.0.0-SNAPSHOT-bin.zip** with all the files needed to create the native-image, this file is send to the native-image buildpack

**Comment by dmikusa-pivotal** [comment]
Yes, so after the artifact resolver locates the artifact, it will copy it to a layer. This is what allows us to persist the artifact across builds and cache it. There is an assumption that the item saved is a zip file (EAR/WAR/JAR typically, but not enforced).

What then happens is that we delete all of the application source code (basically `rm -rf /workspace`) as none of that this needed in the final image & we unzip the artifact that was saved into `/workspace`. The net result is that you end up with the same `/workspace` as if you built locally and performed a `pack build -p my-app.jar`.

There are two ways that we can make this work:

1. If the artifact resolver finds multiple items, it'll zip them all up and store them in the layer in a single zip file. The file would then get extracted into `/workspace` as I described above, but you'd have all of the resolved artifacts.

2. There is some overhead with #1, in that you'd be zipping up artifacts that are possibly already zipped (like if you have a file plus a WAR/JAR). These files may also be fairly large and so the overhead of zipping could be noticed if you have a couple of hundred-megabyte WAR/JAR. We could also look at removing the assumption about what is stored in the layer, i.e. not requiring a ZIP. We could then simply copy all artifacts to the layer. This would complicate the restoration logic though. If there are multiple objects, we'd simply copy all of those back to `/workspace`, however, if there is only one item and it's a ZIP then we'd need to extract that to `/workspace` to retain the current behavior. 

I'd like to go with option #2, but I need to see how much additional effort this requires.

After adding this support I think that having a single artifact will still remain the most common use case, so I worry about the case where someone accidentally has multiple artifacts. This has been something that happens with Gradle projects. If you build locally, then build with buildpacks, you can end up with multiple archives in the build folder. If we change the behavior to support multiple artifacts, we'll need to be careful how we handle this use case. 

I could potentially see adding some protections here, like an env variable `BP_MAVEN_EXPECTED_ARTIFACT_COUNT` which needs to match the number of artifacts that are found. It would default to 1, which would retain the current behavior. How do folks feel about that? Any other suggestions on how we could potentially implement this?

**Comment by jjbustamante** [comment]
Hi @dmikusa-pivotal , 

Thanks for the reply, I just created a [draft PR](https://github.com/paketo-buildpacks/maven/pull/113). the PR is addressing the idea #1 but in order to do that I am using the maven assembly plugin.  I haven't add unit tests yet, but I would like to get any feedback regarding the approach. 

To enable the feature I added the following environment variable `BP_MAVEN_SUPPORT_MULTIPLE_ARTIFACTS` when this environment variable is enable the buildpack will try to inject the distribution xml file to create a zip file from an output folder, defined by `BP_MAVEN_BUILT_ARTIFACT_NATIVE_SOURCE` and configure to default to `native-sources` (for Quarkus) but it can also be configure by the end user

**Comment by dmikusa-pivotal** [comment]
Fantastic, I'll keep an eye out for some PRs. If you have questions, don't hesitate to reach out. Happy to discuss more. Our Slack is a good place for discussions like this. If you're on Slack, we're at https://paketobuildpacks.slack.com. All are welcome to join.
